"""Add location and makeup_artist_name to Event model

Revision ID: 97a4764cdf03
Revises: 861d841e2eaa
Create Date: 2024-11-28 18:57:26.241342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a4764cdf03'
down_revision = '861d841e2eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('makeup_artist_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('makeup_artist_name')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
